services:
  - type: docker-compose
    name: dbs-feedback-system
    dockerComposeFilePath: DBS-Feedback-System/docker-compose.yml
    envFilePath: DBS-Feedback-System/.env
    region: oregon
    branch: master