services:
  - type: docker-compose
    name: universal-feedback-system
    dockerComposeFilePath: Universal-Feedback-System/docker-compose.yml
    envFilePath: Universal-Feedback-System/.env
    region: oregon
    branch: master